Add support to fields.go for protoreflect.EnumNumber with tests
faunists/deal-go pull request #8
Opened 2021-10-05 18:06 UTC by florkbr

Resolves https://github.com/faunists/deal-go/issues/6

2021-10-06 02:49 UTC, thepabloaguilar commented
Hey @florkbr I think I created that issue with the wrong protoreflect type, but I really appreciate your contribution. I won't merge now until I'm sure what we need with Enums. Your contribution will not be for nothing, I'm going to tag this PR with `hacktoberfest-accepted` so it'll count for you as you can see in the image below:
![image](https://user-images.githubusercontent.com/25423500/136132894-1cfc4ac5-495d-4290-b7ce-bdd0aa767b6d.png)

2021-10-06 02:49 UTC, thepabloaguilar commented
Hey @florkbr I think I created that issue with the wrong protoreflect type, but I really appreciate your contribution. I won't merge now until I'm sure what we need with Enums. Your contribution will not be for nothing, I'm going to tag this PR with `hacktoberfest-accepted` so it'll count for you as you can see in the image below:
![image](https://user-images.githubusercontent.com/25423500/136132894-1cfc4ac5-495d-4290-b7ce-bdd0aa767b6d.png)

2021-10-06 03:04 UTC, thepabloaguilar requested changes
Ok, I've made some tests and your solution work as we need proposed in the original issue! Thanks

It has just a minor comment, fix that and we'll ready to go!

2021-10-06 03:04 UTC, thepabloaguilar commented on processors/fields.go
> +	case protoreflect.Message, protoreflect.List, protoreflect.Map:
Please, remove `protoreflect.EnumNumber` from the `TODO` list in beginning of the function!

2021-10-06 14:25 UTC, florkbr commented
@thepabloaguilar no worries! Just exploring what projects are out there and found yours filtering by Go!

Fixed the comment as requested. Let me know if you need anything else!

2021-10-11 14:44 UTC, florkbr commented
@thepabloaguilar bump :)

2021-10-11 19:23 UTC, thepabloaguilar commented
@florkbr the lint check failed!

2021-10-13 18:21 UTC, florkbr commented
@thepabloaguilar sorry! Fixed!

2021-10-14 20:08 UTC, florkbr commented
@thepabloaguilar is the current coverage I've added acceptable? Or do I need to add more?

2021-10-14 20:32 UTC, thepabloaguilar commented
It's acceptable, in fact, `codecov/patch` failed because we don't have any test for the `default` case and you changed that to remove the `protoreflect.EnumNumber`!

I'll merge it tonight

2021-10-15 04:13 UTC, thepabloaguilar approved these changes
Thanks for you contribution @florkbr!!

2021-10-15 04:13 UTC, merged